### ISSUE TITLE
Exposed Service Unit IPs not Hyperlinked

### ISSUE THREAD

**Issue by arosales** [juju/juju-gui#1214] opened 2016-01-14 09:59 UTC
I am using the awesome new juju-gui with circles via cs:~yellow/trusty/juju-gui.  I deployed the RealTime Syslog Analytics bundle:
https://jujucharms.com/realtime-syslog-analytics/bundle

I found that the Service Unit IPs were not hyperlinked even though I exposed the service, in this case Spark.  I think in previous version's of the gui the unit IPs were hyperlinked so I could easily inspect the unit and click the link to open the service
![unit-ip](https://cloud.githubusercontent.com/assets/1707853/12321342/2fc73fb2-bab6-11e5-9c48-688de7e6feeb.png)
 in a new tab.

**Comment by hatched** [comment] 2016-01-14 14:22
Thanks for this report! We will be adding this functionality in a future release. Closing as duplicate of #1187

**Closed by hatched** 2016-01-14 14:22 UTC
