### ISSUE TITLE
Logging in via USSO without permissions gives blank page

### ISSUE THREAD

**Issue by jaycee** [juju/juju-gui#2455] opened 2017-02-15 17:12 UTC
When you log in via USSO identity provider in GIJoe, you end up with no profile and no canvas--just a gray screen with the Juju logo.

![2017-02-15-105931_1918x1042_scrot](https://cloud.githubusercontent.com/assets/26728/22985929/01744276-f378-11e6-95e0-6a2a756ac7b5.png)

This same result occurs when logging in from /new in the deployment flow.

**Comment by hatched** [comment] 2017-02-15 22:41
The original issue was caused by not having the correct permissions when trying to log in. We should handle this better by propagating the error to the user.

**Comment by frankban** [comment] 2017-03-30 13:13
I am not being able to dupe this. Marking as fixed. If it's not, please reopen this bug and provide instructions for reproducing the issue.

**Closed by frankban** 2017-03-30 13:13 UTC
Labels: bug, confirmed
