### ISSUE TITLE
Sometimes when you click into search the x in the corner stays orange.

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1247] opened 2016-01-19 10:19 UTC

**Comment by hatched** [comment] 2016-01-19 15:04
I wasn't able to reproduce this, can you add steps to reproduce please.

**Comment by elvirafigueras** [comment] 2016-01-19 15:25
Joe, could you reproduce it?

-

Elvira Figueras Gabás
UX Designer
Canonical Ltd.

5th Floor, Blue Fin Building | 110 Southwark Street | London | SE1 0SU
ubuntu.com | canonical.com

**Comment by elvirafigueras** [comment] 2016-01-19 15:28
Not sure if this is consistent, but, if I click the search, then
immediately click the cross then click the search again it occurs.

**Comment by hatched** [comment] 2016-01-19 15:33
I can reproduce it following those steps, thanks!

**Comment by kadams54** [comment] 2016-01-25 14:42
Here's what I've done thus far.

Temporary changes to make debugging easier:

1. Update `jujugui/static/gui/src/app/components/header-search/header-search.js` so that the `_closeClasses` function just returns 'header-search__close'. Now the icon doesn't disappear on close, so you can continue to observe its behavior.
2. Update `development.ini` and set `jujugui.combine` to false to make it easier to debug the JS.
3. Setup styles in `jujugui/static/gui/src/app/components/header-search/_header-search.scss` for each of the pseudo classes on the icon, which allows you to observe the hover, active, and focus states in action.

~~~~
    &__close {
        ...

        &:hover {
            border: 1px solid red;
        }

        &:active {
            border: 1px solid blue;
        }

        &:focus {
            border: 1px solid green;
        }
    }
~~~~

Once those changes are in place, walk through the steps described above for reproducing the issue. You can now observe the icon seemingly getting "stuck" in hover mode (that is, having a red border) even when the mouse is not hovering over it.

I tried to reproduce the issue in JSBin:

https://jsbin.com/xayate/edit?html,css,js,output

Since hover does not stick there, I've either missed a key element for reproducing a browser bug, or the problem is in our code and not the browser.

Given that the problem occurs across Firefox, Chrome, and Safari and that I can't reproduce it, I'm inclined to think something wonky is happening in our JS that's preventing the hover state from being cleared. Maybe an event that's not propagating correctly?

**Comment by kadams54** [comment] 2016-01-25 15:34
Solutions that I've tried:

1. Separating the hover stylings from the hidden styling. That is, I added a wrapper `div` element so that I could apply the hover stylings to the wrapper and the hidden to the inner icon. The idea was that the element being hovered was getting hidden, at which point it no longer existed in the layout flow and hover state could not be cleared. This hypothesis was disproved when I disabled the code that hid the icon and found that the hover state was still getting stuck.
2. Firing a `mouseleave` or `mouseout` event as part of closing the icon. The idea here was to try and force the browser to realize that the mouse had moved away from the icon. Alas, didn't work.
3. Looked around quite a bit to see if there was some other sneaky way of forcing the browsers to change or update an element's state. Obviously the web developer tools have a way to do it, but I didn't find any web APIs.

What I didn't try:

Implementing the hover entirely in JS, using `mouseenter`|`mouseleave` events.

**Comment by kadams54** [comment] 2016-07-07 15:25
Just re-tested. The problem doesn't to exist with the current design. Sometimes the shopping cart remains orange for a split second after I leave the hover state (perhaps indicating some performance issues in event handling), but it always went back to grey eventually.

**Closed by kadams54** 2016-07-07 15:25 UTC
Labels: UI
