### ISSUE TITLE
Long charm names break the layout in Machine view 

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2522] opened 2017-02-23 10:45 UTC
To replicate this:
- Add OpenStack In-Containers bundle to the canvas. It could be any that has any charm with a long name
- Go to machine view
- Click the green button to add new units
- The layout of the list is broken with some long charm names, such as openstack-dashboard

Even if this depends on screen sizes, this should behave responsively.

<img width="636" alt="screen shot 2017-02-23 at 10 11 23" src="https://cloud.githubusercontent.com/assets/22299251/23255027/f6d68622-f9b1-11e6-9fb8-8e0de4d00639.png">

**Comment by frankban** [comment] 2017-03-03 12:26
Good catch Clara!

**Comment by hatched** [comment] 2017-03-07 21:35
Duplicate of #2505

**Closed by hatched** 2017-03-07 21:35 UTC
Labels: bug, UI
