### ISSUE TITLE
Move notifications form the bottom left to be centered at the top of the screen in line with the canvas switcher.

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#1250] opened 2016-01-19 10:20 UTC

**Comment by kadams54** [comment] 2016-01-19 20:33
Here's a screenshot of what happens to the "screen too small" notification when moved to the top:

![screen shot 2016-01-19 at 15 32 39](https://cloud.githubusercontent.com/assets/378036/12431198/0ac89c00-bec2-11e5-8d9d-3d819a2f89b8.png)

**Comment by kadams54** [comment] 2016-01-19 20:37
Another question if we do end up moving this to the top: what should the z-index be? Should the notification sit over the header widgets? Over the inspector?

**Comment by hatched** [comment] 2016-01-20 00:13
I would think that this issue would be solved if the z-index was on top of everything.

**Comment by urosj** [comment] 2016-01-21 07:37
@elvirafigueras @Lucapaulina I've vetoed this move to top-center due to usability issues. We can find a solution but it'll land in 2.1 only, not in 2.0.

**Comment by Lucapaulina** [comment] 2016-01-21 10:03
The issue is that too much stuff triggers notifications. Our original
position was top and centre and we moved it to bottom left. It's ok if it
doesn't land, it'll give us time to fix it.

The real issue is that we need to look through what triggers the
notifications and ratify it down, @kadams54 said he would get me the
information.

**Comment by kadams54** [comment] 2016-07-07 15:42
We can revisit notification placement (as well as what events merit notifications) on down the road. Closing for the time being.

**Closed by kadams54** 2016-07-07 15:42 UTC
Labels: UI
