### ISSUE TITLE
Problem connecting to a model

### ISSUE THREAD

**Issue by anthonydillon** [juju/juju-gui#3867] opened 2018-11-02 11:39 UTC
In Firefox, when I click on am AWS model from the profile the GUI errors not being able to connect.

Console output:
```
switching to model:  c51d2429-906a-407a-86df-eae29a67d411 combo:2:1987066
switching model connection combo:2:1993678
closing the model-api inactive connection combo:2:772138
connecting to wss://jimm.jujucharms.com:443/model/c51d2429-906a-407a-86df-eae29a67d411/api combo:2:771563
model connected combo:2:1980622
logging into model-api with macaroons combo:2:1992535
redirection required for loggin into model-api combo:2:1992905
switching model connection combo:2:1993678
closing the model-api connection: wss://jimm.jujucharms.com:443/model/c51d2429-906a-407a-86df-eae29a67d411/api combo:2:772081
cleaning up the model API connection combo:2:748382
model disconnected combo:2:1980588
connecting to wss://1.eu-west-1.aws.jaas.jujucharms.com:443/model/c51d2429-906a-407a-86df-eae29a67d411/api combo:2:771563
Firefox can't establish a connection to the server at wss://1.eu-west-1.aws.jaas.jujucharms.com/model/c51d2429-906a-407a-86df-eae29a67d411/api. combo:2:690124 
```

**Comment by hatched** [comment] 2018-11-02 13:59
It looks like the macaroon you have has expired or is otherwise invalid. If there wasn't a popup to indicate that you have to log in this may be a race condition that will be resolved with the jujulib upgrade that I'm doing.

What you can try is to either clear your cache/localstorage or attempt to connect using an incognito window.

**Comment by anthonydillon** [comment] 2018-11-02 20:37
The issue persists even with a new login on a different browser. Is there any logs I can file or did you wanna get on a hangout to try and diagnosis? I have had this issue a few times in the past 2 weeks.

**Comment by hatched** [comment] 2018-11-02 20:50
I suppose that the best thing might be to have a hangout as we should next look at the websocket frames for any funkyness in there.

**Comment by hatched** [comment] 2019-04-15 22:28
I haven't been able to reproduce this, plz re-open if you can.

**Closed by hatched** 2019-04-15 22:28 UTC
Labels: Feedback: Needed
