### ISSUE TITLE
Juju-Gui fails to parse exported bundle in beta-16

### ISSUE THREAD

**Issue by chuckbutler** [juju/juju-gui#1966] opened 2016-09-01 17:12 UTC
I've used juju-gui to export this bundle, upon re-importing the bundle to re-deploy on another controller (moving from lxd to aws for example)

Screenshot of the error modal in the gui:
![](https://www.evernote.com/l/AX4GdEg57uZERY3ERHi8zSapcGgaDuMr4qAB/image.png)

Error Modal Text:
```
The following errors occurred while retrieving bundle changes: cannot read bundle YAML: cannot unmarshal bundle data: yaml: unmarshal errors: line 1: cannot unmarshal !!str `xenial` into charm.legacyBundleData
```
The bundle in question:
http://paste.ubuntu.com/23120903/

Reproduceable by just attempting to import the bundle from the pastebin

**Comment by hatched** [comment] 2016-09-01 17:13
Thanks for the bug report @chuckbutler but closing as a duplicate of #1937 which has been resolved and will be included in the next GUI release.

**Closed by hatched** 2016-09-01 17:13 UTC
Labels: bug, invalid
