### ISSUE TITLE
After logging in, can't load u/<anotheruser> as it redirects to my profile again

### ISSUE THREAD

**Issue by panlinux** [juju/juju-gui#2940] opened 2017-05-24 18:47 UTC
After I login to https://jujucharms.com, and get redirected to my profile page at https://jujucharms.com/u/ahasenack, I can't seem to display someone else's charms.

If I change the URL to https://jujucharms.com/u/landscape, it ends up redirecting me back to u/ahasenack.

Just before it redirects, I briefly see the URL change to https://jujucharms.com/login/u/landscape, and then I land in https://jujucharms.com/u/ahasenack.

**Comment by hatched** [comment] 2017-05-24 18:48
This appears to be a race condition during the GUI's login sequence as sometimes it retains the previous state after logging into the controller and other times not.

**Comment by huwshimi** [comment] 2017-05-24 23:11
Thanks for reporting this bug. This fix will be available with our next release (duplicate of #2825).

**Closed by huwshimi** 2017-05-24 23:11 UTC
Labels: bug, confirmed
