### ISSUE TITLE
GUI in Juju: Speed up charm fetching on deploy with bundles

### ISSUE THREAD

**Issue by frankban** [juju/juju-gui#1517] opened 2016-04-06 10:32 UTC
When you click to add a bundle to the canvas, the service boxes are displayed very slowly.
The bundlechanges response is sent very quickly by the controller, so I guess this is something happening while creting the ECS or retrieving charm info.

**Comment by Lucapaulina** [comment] 2016-04-06 10:57
It is really slow, it would be amazing if we could speed this up.

**Comment by hatched** [comment] 2016-04-06 14:47
It is slow because it's making a single http request for every charm to the charmstore and the charmstore can be quite slow to respond we should probably perform these queries in parallel to help speed it up.

**Comment by Lucapaulina** [comment] 2016-04-06 15:50
Yeah, latency is a big issue for users so we want to be as snappy as
possible. In our last round of user testing 2 of the participants mentioned
how slow it was it going.

**Comment by hatched** [comment] 2016-04-06 16:32
After some testing it turned out that this issue has been resolved in the develop branch and will be fixed in the next release. It was caused by requesting 'charm-related' for every charm which takes charmstore a very long time to produce for some charms.

**Closed by hatched** 2016-04-06 16:32 UTC
Labels: enhancement

**Comment by Lucapaulina** [comment] 2016-04-06 16:35
Thats sounds promising :)
