### ISSUE TITLE
cannot right-click open or ctrl-click links in store

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2816] opened 2017-04-28 13:56 UTC
When I'm not logged in and I get the store browsing from the server side I can ctrl-click or right-click and open in new tab the links from the store. This includes the tags links on the main store drop down and on the individual search result links. In this way I can search and open a bunch of tabs to process. 

However, when I'm logged in and these links come from the GUI I cannot do this same action. Each click opens in the current tab and there's a lack of way for me to open in a new tab easily as I'd expect.

**Comment by hatched** [comment] 2017-04-28 14:23
The links in the store in the GUI aren't anchor tags, we should change that.

**Comment by huwshimi** [comment] 2017-05-24 05:55
This is a duplicate of #2816.

**Comment by frankban** [comment] 2017-05-24 07:01
@huwshimi this is 2816, copy/paste problem?

**Comment by huwshimi** [comment] 2017-05-24 07:06
@frankban It's a duplicate in another dimension.

It's also a duplicate of #2611.

**Comment by frankban** [comment] 2017-05-24 08:18
Yes, indeed, this is a duplicate, so closing.

**Closed by frankban** 2017-05-24 08:18 UTC
Labels: confirmed, enhancement
