### ISSUE TITLE
the juju-gui served charm details does not include the juju-cards info in the right column

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#2768] opened 2017-04-12 16:28 UTC
Per the title, I wanted to copy/paste the cards info for the openvpn charm and it wasn't there since I was logged in. I had to log out and go back to the openvpn details page to get at it.

**Comment by frankban** [comment] 2017-04-12 16:32
I think this is a duplicate of https://github.com/juju/juju-gui/issues/2726 and this should be included in next release!

**Closed by frankban** 2017-04-12 16:32 UTC
