### ISSUE TITLE
404 error page with model name in search bar

### ISSUE THREAD

**Issue by ClaraLavina** [juju/juju-gui#2602] opened 2017-03-08 15:35 UTC
I got a 404 error when trying to reload the deployment flow page. The name of the model is automatically prepopulated with the model name.

<img width="1271" alt="screen shot 2017-03-08 at 09 31 37" src="https://cloud.githubusercontent.com/assets/22299251/23710487/8a532b00-03e2-11e7-984f-29f622223212.png">

**Comment by frankban** [comment] 2017-03-08 17:17
This seems to be related to an authentication issue we are currently working to fix.
Could you please provide the URL of the original page, and the URL you end up with after refreshing and getting the 404?

**Comment by ClaraLavina** [comment] 2017-03-08 17:39
URL of the original page
https://jujucharms.com/u/cassiocassio/asdfadmymodel/i/inspector/kibana/units/machines/deploy

URL I ended up with after refreshing 
:( sorry I couldn't get it. I tried to replicate the issue and I'm afraid it was because my session expired (I suspect this as screenshot I attached shows Sign in button).

**Comment by ClaraLavina** [comment] 2017-03-09 14:48
Ok, so I tried to replicate the bug this morning and as I suspected this happens when my session has expired.

URL of the original page and URL I end up after refreshing are the same:
https://jujucharms.com/u/cassiocassio/asdfadmymodel/i/inspector/kibana/units/machines/deploy


<img width="1278" alt="screen shot 2017-03-09 at 08 46 21" src="https://cloud.githubusercontent.com/assets/22299251/23755166/1604e09a-04a5-11e7-8fbc-c456ac6b2b6e.png">

**Comment by huwshimi** [comment] 2017-04-03 04:42
Is this a storefront issue? Does it need to get the user to log in and pass the url along to the GUI?

**Comment by frankban** [comment] 2017-04-03 09:20
We already have an issue for changing the default behavior of the store front model page with anonymous users. In this specific case, I think the problem is more auth/cookie related, and this bug can stay here waiting for the auth refactoring to be completed.

**Comment by frankban** [comment] 2017-04-03 09:21
https://github.com/CanonicalLtd/jujucharms.com/issues/447

**Comment by jaycee** [comment] 2017-04-07 14:15
While a better fix is in the pipeline, I think we should have resolved this when we extended the session timeout on storefront to match the implicit session time the GUI uses.

**Closed** 2017-04-07 15:14 UTC
Labels: authentication, bug, high priority
