### ISSUE TITLE
Charms without icons show a broken image

### ISSUE THREAD

**Issue by cmars** [juju/juju-gui#1649] opened 2016-05-12 16:05 UTC
I'm not sure what version of the GUI I have. Juju version is 2.0-beta7.1.

See https://imgur.com/tLFCMVa.

**Comment by hatched** [comment] 2016-05-12 16:36
The version you're using is the latest released version but many changes have been made in development that may resolve this issue. We'll have to investigate to make sure that's the case.

**Comment by cmars** [comment] 2016-05-12 18:20
Built from latest develop branch, and the service circles are now blank: https://imgur.com/rJFBaRQ

**Comment by hatched** [comment] 2016-05-13 16:48
It looks like these were all local charms that don't show the icons.

**Comment by kadams54** [comment] 2016-09-13 12:10
This seems likely related to, if not a dupe of, #1682, which is now resolved. I'm checking to see if this is also resolved.

**Comment by kadams54** [comment] 2016-09-13 12:27
We're back to a broken image icon when a local charm with no icon is uploaded. As such, I'm going to leave this issue open.

**Comment by kadams54** [comment] 2016-09-13 13:27
@frankban and I have talked about making the fix in Juju, at https://github.com/juju/juju/blob/master/apiserver/charms.go#L416. The GUI would request `/charms?url=local:trusty/mycharm-3&icon=1` instead of `/charms?url=local:trusty/mycharm-3&file=icon.svg`. Requests with the file parameter would still 404 if the file isn't found, but if an icon was requested via the icon param, the service would look for an icon and then fall back to the default if none is found.

**Closed** 2016-10-03 12:58 UTC
Labels: bug, Confirmed, needs-feedback
