### ISSUE TITLE
bundle export doesn't show bindings

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3680] opened 2018-06-06 15:18 UTC
Copied from: https://bugs.launchpad.net/juju-gui/+bug/1775328

When we use the gui to export a bundle that included bindings for network spaces, the exported bundle does not include that information. This means that we cannot take that bundle and apply it to another environment, without editing the bundle first to add the binding options.

**Comment by xavpaice** [comment] 2018-06-08 00:32
Duplicate of https://github.com/juju/juju-gui/issues/3360

**Comment by frankban** [comment] 2018-07-30 11:19
Indeed, closing as a duplicate.

**Closed by frankban** 2018-07-30 11:19 UTC
Labels: enhancement
