### ISSUE TITLE
Machine view shows UUID on demo.jujucharms.com in the machine column

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1560] opened 2016-04-15 05:04 UTC
Check out second column.

**Comment by hatched** [comment] 2016-04-15 15:42
The page <title> also shows the UUID. 

The machine view UUID display is caused by this line: https://github.com/juju/juju-gui/blob/develop/jujugui/static/gui/src/app/app.js#L2013 We should just be showing Sandbox instead of the UUID. This was put here for a workflow that was modified and never updated.

**Comment by huwshimi** [comment] 2016-05-05 01:10
I believe this was fixed in #1596. Please reopen this if it can still be reproduced.

**Closed by huwshimi** 2016-05-05 01:10 UTC
Labels: bug, Week 18
