### ISSUE TITLE
relation line stays on gui canvas after service and units removed

### ISSUE THREAD

**Issue by jrwren** [juju/juju-gui#1277] opened 2016-01-22 21:51 UTC
I did the std add wordpress, add mariadb, add relation demo and then I removed both mariadb and wordpress and there is a line from the relation left over.

**Comment by hatched** [comment] 2016-01-26 18:35
I wasn't able to reproduce this, could you reply with some more information about your browser, juju version (or sandbox?), gui version. 

Thanks.

**Comment by hatched** [comment] 2016-05-27 14:51
I'm still not able to reproduce this, it's possible it was fixed in a later version of the GUI. Feel free to re-open if you experience this issue again.

**Closed by hatched** 2016-05-27 14:51 UTC
Labels: bug, needs-feedback
