### ISSUE TITLE
404 request to the charm store when local charms are in the model

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3197] opened 2017-09-08 19:44 UTC
copied from https://bugs.launchpad.net/juju-gui/+bug/1716037

GUI 2.9.2

The gui fails to render charm icons when the charm is from the local source.

Browser console log shows a 404 to the charmstore api referencing the local user and local model name as (sanitized) below

https://api.jujucharms.com/charmstore/v5/~my-local-admin-user/my-local-model-name/meta/any?include=bundle-metadata&include=bundle-machine-count&include=charm-config&include=charm-metadata&include=charm-metrics&include=common-info&include=extra-info&include=id-revision&include=manifest&include=owner&include=published&include=resources&include=revision-info&include=stats&include=supported-series&include=tags

**Comment by frankban** [comment] 2017-09-12 06:22
We already have a bug for the local charms' icons: see https://github.com/juju/juju-gui/issues/3067
However, the cs request needs investigation, so I'll leave this bug open and slightly change its focus. Thanks for reporting!

**Comment by hatched** [comment] 2017-10-04 21:24
The error message in the 404 is caused by how the GUI determines if the user is trying to connect to a model in their namespace, a charm, or bundle. 

Closing this as that's not a bug, and we have another to track the local charm icons.

Thanks for the report.

**Closed by hatched** 2017-10-04 21:24 UTC
Labels: bug, needs-investigation
