### ISSUE TITLE
 local charm deploy via drag and drop doesn't work

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#3284] opened 2017-10-17 21:18 UTC
Please refer to https://bugs.launchpad.net/juju-gui/+bug/1724203 for more details and a copy of the charm used.

**Comment by deephack1982** [comment] 2017-10-18 07:53
I'm the original reporter, let me know if you need anything more to reproduce this.

**Comment by frankban** [comment] 2017-10-18 08:14
Thanks for reporting, and thanks @anastasiamac for moving the issue here!
Is this a duplicate of https://github.com/juju/juju-gui/issues/2546 ?
Does this happen when using JAAS?

**Comment by deephack1982** [comment] 2017-10-19 07:34
Could be related although it mentions clicking upload and being taken to the wrong page. In my case it never displays an upload button but just hangs at "Drop file to add to model". I just tested on JAAS and it doesn't work there either. Could there be something funny with my charm? It works fine from the cli with the following command.

juju deploy ~/charms/builds/paradox-buildslave-linux-puppet --resource paradox-puppet-snap=/home/mark-dickie/Downloads/paradox-puppet-snap_5.3.2_amd64.snap --config=~/Downloads/buildslave-staging-linux-01.yaml

**Comment by clagom** [comment] 2019-07-02 12:39
@hatched @huwshimi Is this still relevant?

**Comment by hatched** [comment] 2019-07-02 17:02
Yes this is still an issue as this type of local charm upload requires additional values to be set which we do not support on the GUI side. I'm going to close this as out of scope for the GUI now.

It should fail more gracefully though.

**Closed by hatched** 2019-07-02 17:02 UTC
Labels: Investigation: Needed
