### ISSUE TITLE
Charm with Terms doesn't work on JaaS

### ISSUE THREAD

**Issue by galgalesh** [juju/juju-gui#2757] opened 2017-04-12 09:10 UTC
This Charm has terms: https://jujucharms.com/u/tengu-team/ssl-termination-proxy/0

When deploying this charm to a model, I get the following errors:

> Could not add requested charm. Server responded with: cannot retrieve charm "cs:~tengu-team/ssl-termination-proxy-0": cannot get archive: cannot get discharge from "https://api.jujucharms.com/identity/v1/discharger": cannot start interactive session: interaction required but not possible.

> Could not deploy the requested application. Server responded with: charm "cs:~tengu-team/ssl-termination-proxy-0" not found.

> Could not add the requested unit. Server responded with: application "ssl-termination-proxy" not found.

Deploying from commandline works:

```
juju deploy cs:~tengu-team/ssl-termination-proxy
Located charm "cs:~tengu-team/ssl-termination-proxy-0".
Deploying charm "cs:~tengu-team/ssl-termination-proxy-0".
Deployment under prior agreement to terms: isrg-lets-encrypt
```

**Comment by frankban** [comment] 2017-04-12 12:09
I confirm this is a regression. Thanks for reporting!

**Comment by frankban** [comment] 2017-04-12 12:32
Actually, rather than a regression, this seems to be a non-complete implementation, as we never acquire the delegatable macaroon from the charm store that would allow us to add the charm with the proper authorization. When getting the "interaction required" required error, we should go ahead, fetch the delegatable macaroon from the charm store for that charm id by doing the usual charm store macaraq, and then try to add a charm again, this time attaching the acquired macaroon.

**Comment by frankban** [comment] 2017-04-12 12:34
For instance, this is the dance I described above, as done by the CLI:
```
14:23:06 TRACE juju.rpc.jsoncodec codec.go:225 -> {"request-id":4,"type":"Client","version":1,"request":"AddCharm","params":{"url":"cs:~tengu-team/ssl-termination-proxy-0","channel":"stable"}}
14:23:07 TRACE juju.rpc.jsoncodec codec.go:120 <- {"request-id":4,"error":"cannot retrieve charm \"cs:~tengu-team/ssl-termination-proxy-0\": cannot get archive: cannot get discharge from \"https://api.jujucharms.com/identity/v1/discharger\": cannot start interactive session: interaction required but not possible","error-code":"unauthorized access","response":{}}
14:23:07 DEBUG httpbakery client.go:244 client do GET https://api.jujucharms.com/charmstore/v5/delegatable-macaroon?id=cs%3A~tengu-team%2Fssl-termination-proxy-0 {
14:23:07 DEBUG httpbakery client.go:592 postFormJSON to https://api.jujucharms.com/identity/v1/discharger/discharge; vals: url.Values{"id":[]string{"redacted"}, "location":[]string{"charmstore"}}
14:23:07 DEBUG httpbakery client.go:244 client do POST https://api.jujucharms.com/identity/v1/discharger/discharge {
14:23:07 DEBUG httpbakery client.go:246 } -> error <nil>
14:23:07 DEBUG httpbakery client.go:592 postFormJSON to https://api.jujucharms.com/terms/discharge; vals: url.Values{"id":[]string{"redacted"}, "location":[]string{"charmstore"}}
14:23:07 DEBUG httpbakery client.go:244 client do POST https://api.jujucharms.com/terms/discharge {
14:23:07 DEBUG httpbakery client.go:246 } -> error <nil>
14:23:08 DEBUG httpbakery client.go:246 } -> error <nil>
14:23:08 TRACE juju.rpc.jsoncodec codec.go:225 -> {"request-id":5,"type":"Client","version":1,"request":"AddCharmWithAuthorization","params":{"url":"cs:~tengu-team/ssl-termination-proxy-0","channel":"stable","macaroon":{"caveats":[{"cid":"declared username frankban"},{"cid":"is-entity cs:~tengu-team/ssl-termination-proxy-0"},{"cid":"active-time-before 2017-04-12T12:24:09.125286299Z"}],"location":"charmstore","identifier":"id","signature":"sig"}}}
14:23:09 TRACE juju.rpc.jsoncodec codec.go:120 <- {"request-id":5,"response":{}}
```

**Comment by frankban** [comment] 2017-05-05 12:56
The implementation of the new bakery and the ability to add charms with terms and add non-public charms has landed to develop, and will be available on production on next update.

**Closed by frankban** 2017-05-05 12:56 UTC
Labels: authentication, bug, confirmed, high priority

**Comment by frankban** [comment] 2017-05-15 10:24
It's not possible to deploy charms with terms and non-public charms from the GUI in production.

**Comment by hatched** [comment] 2018-04-03 15:19
Hello @ulihorn It is back up again, please give it another try.
