### ISSUE TITLE
Able to modify the model name in the header on committed models

### ISSUE THREAD

**Issue by hatched** [juju/juju-gui#3171] opened 2017-08-25 19:54 UTC
To reproduce:

Switch to a committed model, in the model switcher you can modify the model name.

**Comment by frankban** [comment] 2017-08-31 08:52
I cannot reproduce, could you please take another look and describe how to dupe?

**Comment by cassiocassio** [comment] 2017-08-31 13:24
a. **Before** deployment the model-name in the model-switcher is editable.

b. **After** deployment, it is not.

I'm assuming this is correct behaviour, because [controllers do not support renaming models](https://bugs.launchpad.net/juju/+bug/1634262).

@hatched do you see different behaviour?

**Comment by hatched** [comment] 2017-08-31 13:57
I do and I can reliably reproduce it. I'll fix it when I can.

**Comment by huwshimi** [comment] 2017-10-05 05:41
This seems to be fixed now (with the new init changes).

**Closed by huwshimi** 2017-10-05 05:41 UTC
Labels: bug
