### ISSUE TITLE
Export from 2.0.2 GUI creates incorrect boolean values in YAML

### ISSUE THREAD

**Issue by anastasiamac** [juju/juju-gui#2324] opened 2017-01-10 06:38 UTC
From https://bugs.launchpad.net/juju/+bug/1649848:

This is a bundle exported from a basic Kubernetes setup. Note the "falsetrue" and "truetrue" boolean values; that can't be right.

```yaml
series: xenial
applications:
  etcd:
    charm: "cs:~containers/etcd-17"
    num_units: 1
    annotations:
      "gui-x": "1825"
      "gui-y": "741"
    to:
      - "0"
  "kubernetes-worker":
    charm: "cs:~containers/kubernetes-worker-11"
    num_units: 1
    options:
      "enable-cgroups": falsetrue
      ingress: truetrue
      install_from_upstream: falsetrue
    annotations:
      "gui-x": "1430"
      "gui-y": "646"
    to:
      - "1"
  "kubernetes-master":
    charm: "cs:~containers/kubernetes-master-8"
    num_units: 1
    options:
      "enable-dashboard-addons": truetrue
    annotations:
      "gui-x": "640"
      "gui-y": "456"
    to:
      - "0"
  flannel:
    charm: "cs:~containers/flannel-6"
    annotations:
      "gui-x": "2220"
      "gui-y": "836"
  easyrsa:
    charm: "cs:~containers/easyrsa-3"
    num_units: 1
    annotations:
      "gui-x": "1035"
      "gui-y": "551"
    to:
      - "lxd:kubernetes-master/0"
relations:
  - - "kubernetes-master:sdn-plugin"
    - "flannel:host"
  - - "kubernetes-master:kube-api-endpoint"
    - "kubernetes-worker:kube-api-endpoint"
  - - "kubernetes-master:cluster-dns"
    - "kubernetes-worker:kube-dns"
  - - "kubernetes-master:certificates"
    - "easyrsa:client"
  - - "kubernetes-master:etcd"
    - "etcd:db"
  - - "flannel:etcd"
    - "etcd:db"
  - - "kubernetes-worker:certificates"
    - "easyrsa:client"
  - - "kubernetes-worker:sdn-plugin"
    - "flannel:host"
machines:
  "0":
    series: xenial
    constraints: "arch=amd64 cpu-cores=4 mem=7983"
  "1":
    series: xenial
    constraints: "arch=amd64 cpu-cores=2 mem=3951"
```

**Comment by frankban** [comment] 2017-01-10 07:57
Thanks for reporting!

**Comment by fghaas** [comment] 2017-01-10 08:19
@anastasiamac Thanks for copying this over from my earlier LP bug. By the way: if you put that YAML in fenced code blocks, like so:

    ```yaml
    [bunch of YAML]
    ```

... then the formatting is preserved and there's even syntax highlighting. :)

**Comment by frankban** [comment] 2017-01-30 11:04
I was not able to dupe this using current tip. Might be already fixed on next release.

**Comment by hatched** [comment] 2017-02-16 18:23
It appears that this has already been repaired, I also wasn't able to dupe using 2.4.0. If you're still able to reproduce this please feel free to reopen this issue.

**Comment by burton-swan** [comment] 2017-03-03 06:03
This issue can be reproduced on juju gui 2.4.2, e.g.:

    options: 
      logrotate_dateext: truetrue
      use_rsyslog: falsetrue

Attachment is the yaml file I got.
[default-2017-03-03.yaml.zip](https://github.com/juju/juju-gui/files/815904/default-2017-03-03.yaml.zip)

**Comment by hatched** [comment] 2017-03-03 14:50
Hmm, I'm still not able to reproduce. @burton-swan was this using one of the kubernetes bundles? Can you outline the steps taken to reproduce?

**Comment by burton-swan** [comment] 2017-03-06 03:04
Sure, this issue can be reproduced on both AWS and local lxd controllers, although I didn't use kubernetes bundles.

Deploy 2 basic charms, on AWS I deployed cs:trusty/apache2-20 and cs:trusty/wordpress-4; on local lxd I deployed cs:trusty/mediawiki-3 and cs:trusty/mysql-29.

Create a bundle between these 2 charms via juju gui 2.4.2, e.g.:
AWS: wordpress:website - apache2:website-cache
Local lxd: mediawiki:db - mysql:db

Click Export button on the top left bar, save the yaml file, errors as this bug described will show up in the file.

Procedures (AWS) list here for reference:
$ juju set-default-region aws us-east-1
$ juju bootstrap aws mycloud_test
$ juju deploy cs:trusty/apache2-20
$ juju deploy cs:trusty/wordpress-4
$ juju gui

login the page, drag the link to create a bundle between apache2-20 and wordpress-4, Commit Changes -> Deploy, then click Export button, save the yaml file generated.

Revelant links:
https://jujucharms.com/docs/stable/getting-started
https://jujucharms.com/docs/stable/help-aws
https://jujucharms.com/docs/2.1/controllers-gui
https://jujucharms.com/docs/2.1/charms-bundles

**Comment by lathiat** [comment] 2017-03-14 04:55
This happened to me when I used conjure-up to deploy openstack-nova-lxd onto a local lxd server.

ubuntu xenial 16.04
conjure-up 2.1.1 (from snappy)
juju 2.1.1-xenial-amd64 (from ppa:juju/stable)

did not customise anything, just deployed, ran juju gui and exported the bundle

**Comment by kadams54** [comment] 2017-03-14 15:21
This bug only seems to happen if you deploy the charms via the CLI; if you deploy them from the GUI, the boolean config values are fine. We'll continue investigating a fix.

**Comment by fghaas** [comment] 2017-03-14 15:27
@kadams54 Thanks for the update!

**Comment by frankban** [comment] 2017-03-15 10:17
This seems to be related to a minification problem. That would explain also why it's not possible to dupe the bug using guiproxy.

**Closed** 2017-03-15 13:56 UTC
Labels: bug
