### ISSUE TITLE
MV2 add unit doesn't work

### ISSUE THREAD

**Issue by urosj** [juju/juju-gui#1108] opened 2015-12-18 06:18 UTC
Adding units to a service from inspector works, adding units in MV2 opens up a list of services, one can write the number of units there but "add units" button below the list of services in MV2 does nothing.

**Comment by hatched** [comment] 2015-12-18 23:14
I haven't been able to reproduce this. If you are able to reproduce this again, please re-open.

**Comment by huwshimi** [comment] 2015-12-19 05:36
This can be reproduce when using the admin model.

**Comment by huwshimi** [comment] 2015-12-21 01:10
It appears that there is a console error when trying add units when there are committed machines.

**Comment by hatched** [comment] 2015-12-21 01:15
```
Uncaught TypeError: Cannot read property 'get' of null
utils.addGhostAndEcsUnits @ combo?app/assets/javascripts/yui/widget-stack/widget-stack.js&app/assets/javascripts/yui/panel/pane…:2572
(anonymous function) @ combo?app/components/scale-service/scale-service.js&app/components/inspector-confirm/inspector-conf…:2473
_handleAddUnits @ combo?app/components/scale-service/scale-service.js&app/components/inspector-confirm/inspector-conf…:2469
_handleClick @ combo?app/assets/javascripts/yui/event-valuechange/event-valuechange.js&app/assets/javascripts/yui/…:5040
ReactErrorUtils.invokeGuardedCallback @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:10095
executeDispatch @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:2828
executeDispatchesInOrder @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:2851
executeDispatchesAndRelease @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:2291
executeDispatchesAndReleaseTopLevel @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:2302
forEachAccumulated @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:17853
EventPluginHub.processEventQueue @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:2507
runEventQueueInBatch @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:10120
ReactEventEmitterMixin.handleTopLevel @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:10136
handleTopLevelWithoutPath @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:10234
handleTopLevelImpl @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:10214
Mixin.perform @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:17280
ReactDefaultBatchingStrategy.batchedUpdates @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:8851
batchedUpdates @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:15356
ReactEventListener.dispatchEvent @ combo?app/assets/javascripts/react-with-addons.js&app/assets/javascripts/react-dom.js&app/assets/ja…:10345
```

**Comment by hatched** [comment] 2015-12-21 02:33
So the root issue is that the logic which determines the service name to add units to splits on "-". The reason this was appearing only in the 'admin' model was because it was the only one with the "juju-gui" charm.

**Closed** 2015-12-21 03:44 UTC
Labels: bug, critical
