### ISSUE TITLE
How come I still see the "Log in to the charm store" button?

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2682] opened 2017-03-28 11:00 UTC
![screen shot 2017-03-28 at 11 52 01](https://cloud.githubusercontent.com/assets/12827541/24401844/edc50228-13ad-11e7-9fb5-cabec250694d.png)

It shows up in @Lukewh's profile too but not in @spencerbygraves

**Comment by ClaraLavina** [comment] 2017-03-28 11:03
Same with me...

<img width="1280" alt="screen shot 2017-03-28 at 12 02 00" src="https://cloud.githubusercontent.com/assets/22299251/24401972/7fdfd7d2-13ae-11e7-8737-2efc3e6958f9.png">

**Comment by urosj** [comment] 2017-03-28 11:07
Duplicate of https://github.com/juju/juju-gui/issues/2564

**Closed by urosj** 2017-03-28 11:07 UTC
