### ISSUE TITLE
A notification should not disappear if I am hovering over it

### ISSUE THREAD

**Issue by elvirafigueras** [juju/juju-gui#2112] opened 2016-10-07 12:21 UTC
A common user behaviour is to attempt to hover over canvas notifications to read and assimilate their content better, expecting that they will remain there if they do so but they don't.

Could we look into this?

**Comment by kadams54** [comment] 2016-10-10 16:21
@elvirafigueras Non-error notifications should either close on their own, after 3 seconds, or on click. Error notifications should only close on click. Which notification type was closing on hover?

**Comment by anthonydillon** [comment] 2016-10-10 17:20
The issue is that non error notifications are still self destroying, even
when hovered by a mouse. Giving the user no chance to haul the destruction
and allowing them time to read the notification.

A fix would be the stop the timer on mouse over and restart from 0 when
mouse leaves.

**Comment by kadams54** [comment] 2016-10-11 15:17
@anthonydillon Ah, got it. Sounds good.

**Closed** 2016-10-19 20:41 UTC
Labels: UI
