### ISSUE TITLE
A save changes button of charm configure doesn't exist in the newlest version GUI.

### ISSUE THREAD

**Issue by sa-kura** [juju/juju-gui#3035] opened 2017-06-26 10:05 UTC
A save changes button of charm configure doesn't exist in the newlest version GUI.
Therefore, we can't change the cofiguration.
I used Juju 2.2.0 and webui 2.7.3.

This problem does not occur in Juju 2.1.2 and webui 2.4.4.

**Comment by frankban** [comment] 2017-06-26 10:17
Confirmed, thanks for reporting this regression!

**Comment by frankban** [comment] 2017-06-26 10:20
Actually, the buttons are displayed once you change any value in the config. Could you confirm that it works for you?

**Comment by sa-kura** [comment] 2017-06-26 10:51
Thank you for your response.
I changed any value in the config, but button was not displayed.

**Comment by frankban** [comment] 2017-06-26 11:07
Ok, so what browser are you using? On what OS? My experience with Chrome and Firefox under Ubuntu is that I click to modify a config value, and once it is changed the two buttons (cancel and save) appears at the bottom of the config panel.

**Comment by sa-kura** [comment] 2017-06-26 11:32
I used Chrome(Version 59.0.3071.109 64bit) and Windows10 Pro 1607

**Comment by frankban** [comment] 2017-06-26 11:33
Ok, thanks a lot for your feedback, we'll investigate the bug on this scenario then!

**Comment by jlpnetworx** [comment] 2017-07-02 22:50
Very same problem here with  Juju 2.1.2, webui 2.4.4 and Windows 10, both Chrome and Firefox.

**Comment by hatched** [comment] 2017-07-03 02:20
Unfortunately I am not able to reproduce this issue, I have tried OSX/Ubuntu/Win Chrome/FF/Safari with GUI 2.7.3 and the 2.7.4 that's running on JAAS (https://jujucharms.com/new). Are there specific charms that this issue presents on? Or do changes to any of the configuration values on any of the charms fail to show the buttons?

From JAAS with the Elasticsearch charm:
<img width="317" alt="screen shot 2017-07-02 at 8 16 47 pm" src="https://user-images.githubusercontent.com/532033/27775890-6c9f9dc8-5f63-11e7-9186-4b504160751f.png">

It would also be quite helpful if you could try with JAAS to see if you can reproduce the issue there.

**Comment by hatched** [comment] 2017-07-03 02:36
Also, if you are able to give it another try, if you wouldn't mind taking a look in the browser console (can be opened using ctrl+shift+i) and paste any error messages that may be there after a config option has been changed. Thanks!

**Comment by sa-kura** [comment] 2017-07-03 05:41
When this issue occured, I used Openstack Base-49.
So I have tried Openstack Base-49 on JAAS.
But I am not able to reproduce this issue on JAAS.
(The buttons are displayed)

I reproduced this issue and got error messages on browser conole of my environment.

`
combo?app/components/inspector/change-version/change-version-min.js&app/components/boolean-config/b…:15 Uncaught TypeError: Cannot read property 'toString' of undefined
   at Object.keys.forEach (combo?app/components/inspector/change-version/change-version-min.js&app/components/boolean-config/b…:15)
   at Array.forEach (<anonymous>)
   at Object._getChangedValues (combo?app/components/inspector/change-version/change-version-min.js&app/components/boolean-config/b…:15)
   at Object._getChangedConfig (combo?app/components/inspector/change-version/change-version-min.js&app/components/boolean-config/b…:15)
   at Object._handleOnChange (combo?app/components/inspector/change-version/change-version-min.js&app/components/boolean-config/b…:15)
   at Object.setState (combo?app/components/inspector/change-version/change-version-min.js&app/components/boolean-config/b…:13)
   at e.notifyAll (combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:26)
   at o.close (combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:28)
   at o.closeAll (combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:29)
   at o.perform (combo?app/assets/javascripts/react-with-addons.min.js&app/assets/javascripts/react-dom.min.js&app/a…:29)
`

**Comment by hatched** [comment] 2017-07-03 06:28
ahah! There we go, now I can reproduce it.

This issue has actually already been resolved in GUI 2.7.4 which is why you didn't see the issue in JAAS. This version should be rolling out to Juju shortly at which point you'll be able to run `juju upgrade-gui` and it'll be resolved.

I'll report back once this has been completed. Sorry for the inconvenience.

**Comment by frankban** [comment] 2017-07-03 07:36
Cool, thanks you both for investigating further!

**Closed by frankban** 2017-07-03 07:36 UTC
Labels: bug, high priority

**Comment by richardsith** [comment] 2017-07-03 10:39
confirm on JAAS not issue, instead on Juju Gui (ver. 2.7.3) the problem is present. Look the pictures:

JUJU Gui
![screen shot 2017-07-03 at 12 38 28](https://user-images.githubusercontent.com/9977215/27789349-94fbc70e-5fec-11e7-8541-f16fe9d6813e.png)

JAAS
![screen shot 2017-07-03 at 12 38 34](https://user-images.githubusercontent.com/9977215/27789350-951240d8-5fec-11e7-9394-69a057fae07a.png)

**Comment by hatched** [comment] 2017-07-03 14:32
The GUI in Juju has been updated to 2.7.4 which I've confirmed resolves this issue.

To update the version of the GUI in your controller you can run `juju upgrade-gui`.

Thanks all for the help!

**Comment by richardsith** [comment] 2017-07-03 15:06
perfect I've done that and the button now is displayed.
Thanks a lot

**Comment by sa-kura** [comment] 2017-07-04 08:44
I updated  the version of the GUI of my environment.
I confirmed resolves this issue.
Thanks all.
