### ISSUE TITLE
"status" button in GUI takes user to incomplete broken page Edit

### ISSUE THREAD

**Issue by mitechie** [juju/juju-gui#3901] opened 2019-03-18 13:56 UTC
Copied from: https://bugs.launchpad.net/juju/+bug/1820559

# Steps to reproduce

* Open up the GUI
* Select a model which has a deployment (or failed deployment)
* In the menu which says "16 applications | 4 machines | status", click status

# Expected result

I can see a status of the deployment.
I can see what has finished deploying, what is still in progress, what has failed and why.

# Actual result

I still see the graph of connected nodes. But all text has disappeared.
Clicking on any node highlights that circle, but no text appears.

There are no navigation buttons or information buttons anywhere.

I cannot see the status of anything.
I still have no idea why my deployment failed.

The nodes are orange, which means deployment is in progress. But MAAS has been showing "deployment failed" for the last hour. So I can't trust the colours. I cannot see any logs to debug what went wrong.

No error messages or debug info is printed in the browser console.
![juju-status-printscreen](https://user-images.githubusercontent.com/75915/54535047-1175c980-4964-11e9-9bed-df3a70c73912.png)

**Comment by hatched** [comment] 2019-03-18 16:13
This one appears to be related to a JS error in the view layer. Without the browser logs we may be unable to determine the true cause of it.

**Comment by mlda065** [comment] 2019-03-19 00:08
I'm the person who made that original launchpad issue. What logs do you need?

Nothing appears in the browser console. (`console.log` output)

**Comment by hatched** [comment] 2019-03-20 16:40
Hmm interesting, yes usually there should be issues logged into the browser console. I'll see what I can do about reproducing this locally.

**Comment by mlda065** [comment] 2019-04-11 06:37
When I see this, selecting another model and then selecting the original does not fix the problem.

Refreshing the page does fix the problem.

So I think the issue is about some stale data.

**Comment by clagom** [comment] 2019-07-02 12:59
@hatched Is this still relevant?

**Comment by hatched** [comment] 2019-07-02 17:11
I'm not able to reproduce this. Closing for now. If we can find steps to reproduce this then we can re-open.

**Closed by hatched** 2019-07-02 17:11 UTC
Labels: Investigation: Needed
