### ISSUE TITLE
There is no favicon on the GUI

### ISSUE THREAD

**Issue by faooful** [juju/juju-gui#2211] opened 2016-11-21 15:44 UTC

**Comment by faooful** [comment] 2016-11-21 16:07
![image](https://cloud.githubusercontent.com/assets/2169216/20490078/a3c14aae-b004-11e6-801b-f4cd7ecde8e9.png)

**Comment by hatched** [comment] 2016-11-21 16:09
There is one shown in the code and I can see it in Chrome/FF in Ubuntu. Will have to investigate further as to why it's not shown in OSX.

**Comment by jrwren** [comment] 2016-12-01 14:46
It does not show in GISF either. In chrome on osx.

in html: <link rel="shortcut icon" href="/static/gui/build/app/favicon.ico">

in console: GET https://jujucharms.com/static/gui/build/app/favicon.ico/ 404 (Not Found)

Maybe the issue is something inserting a trailing slash?

https://jujucharms.com/static/gui/build/app/favicon.ico responds with 302 to https://jujucharms.com/static/gui/build/app/favicon.ico/ 

https://jujucharms.com/static/gui/build/app/favicon.ico/ responds with 404.

**Comment by hatched** [comment] 2016-12-01 16:30
Thanks @jrwren this has been resolved in the release going out today.

**Closed by hatched** 2016-12-01 16:30 UTC

**Comment by jaycee** [comment] 2016-12-01 17:06
The GUI was recently fixed for this, and the fix will roll out with GISF soon.

On Thu, Dec 01, 2016 at 06:46:25AM -0800, Jay R. Wren wrote:
> It does not show in GISF either. In chrome on osx.
> 
> in html: <link rel="shortcut icon" href="/static/gui/build/app/favicon.ico">
> 
> in console: GET https://jujucharms.com/static/gui/build/app/favicon.ico/ 404 (Not Found)
> 
> Maybe the issue is something inserting a trailing slash?
> 
> https://jujucharms.com/static/gui/build/app/favicon.ico responds with 302 to https://jujucharms.com/static/gui/build/app/favicon.ico/ 
> 
> https://jujucharms.com/static/gui/build/app/favicon.ico/ responds with 404.
> 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/juju/juju-gui/issues/2211#issuecomment-264191190

--
